sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t arfatahmad/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true arfatahmad/react-test npm test -- --coverage
after_success: 
  - docker build -t arfatahmad/multi-client ./client
  - docker build -t arfatahmad/multi-nginx ./nginx
  - docker build -t arfatahmad/multi-server ./server
  - docker build -t arfatahmad/multi-worker ./worker
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push the images to docker hub
  - docker push arfatahmad/multi-client
  - docker push arfatahmad/multi-nginx
  - docker push arfatahmad/multi-server
  - docker push arfatahmad/multi-worker
